---
- name: upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
    state:  latest
    production: yes