version: 2.1
jobs:
  print_hello:
    docker:
      - image:  circleci/node:13.8.0
    steps:
      - run:  echo hello
  print_world:
    docker:
      - image:  circleci/node:13.8.0
    steps:
      - run:  echo world

      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
         requires:
           - print_hello

          

