version: 2.1
orbs: 
  node: 'circleci/node:4.1'
  slack: circleci/slack@4.1.0

jobs:
  build_frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Build-frontend
          command: |
            cd frontend
            npm install
            npm run build  

  
  build_backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Build-backend
          command: |
            cd backend
            npm install
            npm run build    
               
  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Test-frontend
          command: |
            cd frontend
            npm install
            npm run test 
     
  test-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Test-backend
          command: |
            cd backend
            npm install
            npm run test 
      
  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Analyze-frontend
          command: |
            cd frontend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical

  scan-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Analyze-backend
          command: |
            cd backend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical
     
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: udapeople-app-cicd
          event: pass
          template: success_tagged_deploy_1

workflows:
  default:
    jobs:
      - build_frontend
      - build_backend
      - test-frontend:
          requires: [build_frontend]
      - test-backend:
          requires: [build_backend]
      - scan-frontend:
          requires: [build_frontend]
      - scan-backend:
          requires: [build_backend]
      - deploy:
          context: slack-udapeople
          requires: [scan-backend]
          

