version: 2.1
orbs: 
  slack: circleci/slack@4.10.1

commands:
  failure:
    steps:
      - slack/notify:
          channel:  udapeople-app-cicd
          event:  fail
          template: basic_fail_1

  success:
    steps:
      - slack/notify:
          channel:  udapeople-app-cicd
          event:  pass
          template: basic_success_1          

  deploy:
    steps:
      - slack/notify:
          channel:  udapeople-app-cicd
          event:  pass
          template: basic_success_1 

jobs:
  build_frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Build-frontend
          command: |
            cd frontender
            npm install
            npm run buildyg
      - failure
      - success
      - deploy
  
  build_backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Build-backend
          command: |
            cd backend
            npm install
            npm run build    
      - failure
      - success
      - deploy

  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Test-frontend
          command: |
            cd frontend
            npm install
            npm run test 
      - failure
      - success
      - deploy

  test-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Test-backend
          command: |
            cd backend
            npm install
            npm run test 
      - failure
      - success
      - deploy

  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Analyze-frontend
          command: |
            cd frontend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical
      - failure
      - success
      - deploy

  scan-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Analyze-backend
          command: |
            cd backend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical
      - failure
      - success
      - deploy 

workflows:
  default:
    jobs:
      - build_frontend
      - build_backend
      - test-frontend:
          requires: [build_frontend]
      - test-backend:
          requires: [build_backend]
      - scan-frontend:
          requires: [build_frontend]
      - scan-backend:

          

          
          
          

