version: 2.1
orbs: 
  slack: circleci/slack@4.10.1

commands:
  failure:
    steps:
      - slack/notify:
          channel:  udapeople-app-cicd
          event:  fail
          template: basic_fail_1

jobs:
  build_frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Build-frontend
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths:  [frontend/node_modules]
          keys:   [frontend-builder]
      - failure
  
  build_backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Build-backend
          command: |
            cd backend
            npm install
            npm run build    
      - save_cache:
          paths:  [backend/node_modules]
          keys:   [backend-builder]
      - failure

  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Test-frontend
          command: |
            cd frontend
            npm install
            npm run test 
      - save_cache:
          paths:  [frontend/node_modules]
          keys:   [frontend-builder]
      - failure

  test-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Test-backend
          command: |
            cd backend
            npm install
            npm run test 
      - save_cache:
          paths:  [backend/node_modules]
          keys:   [backend-builder]
      - failure

  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Analyze-frontend
          command: |
            cd frontend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical
      - save_cache:
          paths:  [frontend/node_modules]
          keys:   [frontend-builder]
      - failure

  scan-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Analyze-backend
          command: |
            cd backend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical
      - save_cache:
          paths:  [backend/node_modules]
          keys:   [backend-builder]
      - failure

  success:
    docker:
      - image:  'cimg/base:stable'
    steps:
      - slack/notify:
          channel:  udapeople-app-cicd
          event:  pass
          template: success_tagged_deploy_1
      - slack/notify:
          channel:  udapeople-app-cicd
          event:  pass
          template: basic_success_1    

workflows:
  default:
    jobs:
      - build_frontend
      - build_backend
      - test-frontend:
          requires: [build_frontend]
      - test-backend:
          requires: [build_backend]
      - scan-frontend:
          requires: [build_frontend]
      - scan-backend:
          requires: [build_backend]
      - success:
          context: slack-udapeople
          requires: 
            - scan-backend
          
          
          

