version: 2.1
orbs: 
  slack: circleci/slack@4.10.1

commands:
  notify_on_failure:
    steps:
      - slack/notify:
          event: fail
          channel: Udapeople CI/CD
          template: basic_fail_1
  
jobs:

  build_frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Build-frontend
          command: |
            cd frontend
            npm install
            npm run build    
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-builder
      - notify_on_failure:

  build_backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Build-backend
          command: |
            cd backend
            npm install
            npm run build    
      - save_cache:
          paths: [backend/node_modules]
          key: backend-builder
      - notify_on_failure:

  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Test-frontend
          command: |
            cd frontend
            npm install
            npm run test 

  test-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Test-backend
          command: |
            cd backend
            npm install
            npm run test    
  
  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-builder]
      - run:
          name: Analyze-frontend
          command: |
            cd frontend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical
            
  scan-backend:
    docker:
      - image:  cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-builder]
      - run:
          name: Analyze-backend
          command: |
            cd backend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical

  notify_on_success:
    docker:
      - image: cimg/base:stable
    steps:
    - slack/notify:
        event: pass
        channel: Udapeople CI/CD
        template: success_tagged_deployment_1

workflows:
  default:
    jobs:
      - build_frontend
      - build_backend
      - test-frontend:
          requires: [build_frontend]
      - test-backend:
          requires: [build_backend]
      - scan-frontend:
          requires: [build_frontend]
      - scan-backend:
          requires: [build_backend]
      - notify_on_success:
          requires: [build_backend]

          

